--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/neo/Wallpaper/wall7.png"

-- Special
background="#040408"
foreground="#cfdfee"
cursor="#cfdfee"

-- Colors
color0="#040408"
color1="#4B4A42"
color2="#1D639B"
color3="#2C6FAC"
color4="#538AB3"
color5="#2B90E6"
color6="#5DA5EA"
color7="#cfdfee"
color8="#909ca6"
color9="#4B4A42"
color10="#1D639B"
color11="#2C6FAC"
color12="#538AB3"
color13="#2B90E6"
color14="#5DA5EA"
color15="#cfdfee"
