# Shell variables
# Generated by 'wal'
wallpaper='/home/neo/Wallpaper/wall7.png'

# Special
background='#040408'
foreground='#cfdfee'
cursor='#cfdfee'

# Colors
color0='#040408'
color1='#4B4A42'
color2='#1D639B'
color3='#2C6FAC'
color4='#538AB3'
color5='#2B90E6'
color6='#5DA5EA'
color7='#cfdfee'
color8='#909ca6'
color9='#4B4A42'
color10='#1D639B'
color11='#2C6FAC'
color12='#538AB3'
color13='#2B90E6'
color14='#5DA5EA'
color15='#cfdfee'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
